// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgRCHP5ytrizU4GjfkHD8IX6LTac36fA',
    appId: '1:885169577226:web:c024aca559e18188512ef3',
    messagingSenderId: '885169577226',
    projectId: 'tuturedu-app',
    authDomain: 'tuturedu-app.firebaseapp.com',
    storageBucket: 'tuturedu-app.firebasestorage.app',
    measurementId: 'G-8HCJ2NRFCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDhydKrJTAGxURxj-0YM8p1_imkBiNrg',
    appId: '1:885169577226:android:f2b9fba3f159532b512ef3',
    messagingSenderId: '885169577226',
    projectId: 'tuturedu-app',
    storageBucket: 'tuturedu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsA7c0mZ-M2HFp9YinKXeIQoC8juE01I',
    appId: '1:885169577226:ios:b43d29958f72bbb0512ef3',
    messagingSenderId: '885169577226',
    projectId: 'tuturedu-app',
    storageBucket: 'tuturedu-app.firebasestorage.app',
    iosBundleId: 'com.example.tuturedu',
  );
}
